name: Build and Release Legba Binary

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-use/setup-rust@stable
      with:
        toolchain: stable
        
    - name: Install dependencies for linux
      run: |
        sudo apt-get update
        sudo apt-get install -y libsmbclient-dev pkg-config
        
    - name: Install mingw toolchain for windows cross-compiling
      run: |
        sudo apt-get install -y gcc-mingw-w64-x86-64
    
    - name: Add Windows target for cross-compiling
      run: |
        rustup target add x86_64-pc-windows-gnu
    
    - name: Build Legba binary for linux
      run: |
        cargo build --release

    - name: Build Legba binary for Windows
      run: | 
        cargo build --release --target x86_64-pc-windows-gnu

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./target/release/legba
          ./targer/x86_64-pc-windows-gnu/release/legba.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
